### ISSUE TITLE
[Exploration] Post user-testing Teams & IA exploration

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-platform#1108]
Before Morgana goes, we'd like to get her perspective on what she'd like to get her high-level perspective (and visual ideation) on what she and her users would most like to get out of a Teams experience.

## Topic 1: Team view

**Some questions that came up around Teams during our kick off call:**

- How might we use login to separate public and authenticated content?
- How can non-admins contribute team content?
- How do core assets interact with team assets? (Is core Carbon a default and I’m adding the other things… or do the other things live separately)

Morgana is specifically interested in creating/curating a team, selecting assets and any type of content, contribution model and how might a team admin approve/review new content contributed by team members.

## Topic 2: IA issues

Morgana has some research-backed concerns (that Tracey and I share) about the current platfrom IA. Her team just conducted a thorough research with Cloud PAL users (dev and designers) about the current PAL experience. **Jumping between asset usage documentations quickly (be it to answer question, understand differences between similar assets, or discovery) is a must,** (Shaun Lynch brought this up in our user testing as well). The current Carbon next experience doesn’t support that type of usage as well as what we have today.

## Deliverables

These are subject to change/refinement:

- [ ] High level, very low fidelity wires of UXA flows
- [ ] Supporting written proposal
- [ ] Knowledge transfer — identify another Cloud PAL team member to support this work after Morgana's transition

**Comment by yumeforever** [comment]
(Comment is WIP)

## Topic 2: IA Issue

### The problem
<img width="1244" alt="CleanShot 2022-08-03 at 17 20 56@2x" src="https://user-images.githubusercontent.com/3612533/182646199-ac6d0186-95d1-48b8-aad0-d1f4f07343a8.png">

**Comment by yumeforever** [comment]
## Topic 1: Teams

🗓 Update Friday September 08 2022
📹 [Playback recording](https://ibm.box.com/s/eqzmq2rnkco9e00z92ihq7zpfhkiwt5i)

[<img width="507" alt="CleanShot 2022-09-09 at 11 39 38@2x" src="https://user-images.githubusercontent.com/3612533/189321024-a20c4b6d-2d5e-4c62-90ef-003aba881f51.png">](https://www.figma.com/file/LxJwxtiImBPdBVagvg6bmp/Team-experience-explorations?node-id=0%3A1)

### User flow

An IBM creator is able to find the guidelinesn and tools they are required to use in order to create the user experience for IBM clients. An IBM creator is able to confidently find and join the correct system to do their work
An IBM creator is able to know what has changed, added or removed from the systems they joined so that they are sure to use the latest best practices  and assets in their user experiences

<img width="1088" alt="CleanShot 2022-09-09 at 11 37 23@2x" src="https://user-images.githubusercontent.com/3612533/189320961-f7ce19a8-566e-48fb-a442-bcd9a75ae10d.png">

### Admin flow

An IBM local system admin is able to curate, ensure quality, and freshnesss of their content so that their users always have the latest content available to do their work
An IBM local system admin is able to  review, accept, reject and request changes to updates proposed by the community so that the local system is always evolving
<img width="1088" alt="CleanShot 2022-09-09 at 11 37 40@2x" src="https://user-images.githubusercontent.com/3612533/189320951-93692faf-8307-4585-888b-ec1801d8c953.png">
