### ISSUE TITLE
Update Copy

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-platform#1140]
https://next.carbondesignsystem.com/about-carbon/how-carbon-works#the-carbon-ecosystem

`current`

The Carbon ecosystem

Carbon is a system of systems. At the epicenter lies the core system, with elements, assets, code, design kits, and guidelines intended as a base for the widest variety of situations. These assets are open source and can be easily extended or adapted.

Teams at IBM also create local systems that depend on and extend the core system for specific use cases. For example, [Carbon for IBM.com](https://www.ibm.com/standards/carbon/) is a local system that specializes in an editorial experience, whereas [Carbon for IBM Products](https://pages.github.ibm.com/cdai-design/pal/) provides assets and guidance specific to the product experience.

Some local systems are open source while others require IBM employee authentication to view.

It is recommended that you start with the core system and whichever local systems are most relevant to your team. Catalogs for [components](https://next.carbondesignsystem.com/assets/components), [patterns](https://next.carbondesignsystem.com/assets/patterns), [functions](https://next.carbondesignsystem.com/assets/functions), and [templates](https://next.carbondesignsystem.com/assets/templates) allow you to explore everything Carbon has to offer, with filters to find exactly what you need.

If you’re ready to get started with Carbon, check out our guidance for [designing](https://next.carbondesignsystem.com/designing/get-started) and [developing](https://next.carbondesignsystem.com/developing)

**Comment by mjabbink** [comment]
`expected`


The Carbon ecosystem

Carbon is a system of systems. At the epicenter lies the core system, with elements, assets, code, design kits, and guidelines intended as a base for the widest variety of situations. These assets are open source and can be easily extended or adapted.

Teams at IBM also create local systems that depend on and extend the core system for specific use cases. For example, [Carbon for IBM.com](https://www.ibm.com/standards/carbon/) is a local system that specializes in an editorial experience, whereas [Carbon for IBM Products](https://pages.github.ibm.com/cdai-design/pal/) provides assets and guidance specific to the product experience. Some local systems are open source while others require IBM employee authentication to view.

It is recommended that you start with the core system and whichever local systems are most relevant to your team. Catalogs for [components](https://next.carbondesignsystem.com/assets/components), [patterns](https://next.carbondesignsystem.com/assets/patterns), [functions](https://next.carbondesignsystem.com/assets/functions), and [templates](https://next.carbondesignsystem.com/assets/templates) allow you to explore everything Carbon has to offer, with filters to find exactly what you need.

If you’re ready to get started with Carbon, check out our guidance for [designing](https://next.carbondesignsystem.com/designing/get-started) and [developing](https://next.carbondesignsystem.com/developing)



.
.
.
.
In the first paragraph, there could be mention of contributing back to the system 

e.g. 

.... These assets are open source and can be easily extended or adapted and also reused by other teams in the ecosystem

**Comment by mjabbink** [comment]
@aubrey-oneal @jeanservaas 

The main point of this (as most of my copy edits) is the continued use of hard returns when not necessary. 

The below sentence is a continuation of the preceding paragraph. It does not need to be its own sentence between two paragraphs. 

e.g.
“Some local systems are open source while others require IBM employee authentication to view.”

**Comment by aubrey-oneal** [comment]
Hi Mike, in the this case I would not take out the carriage return. In my content practice I follow several guidelines and the Content hierarchy guidelines that Tom has written does such a great job of ensuring that the content we write is scannable. i.e. [Content hierarchy 1d](https://pages.github.ibm.com/cdai-design/pal/content/content-heuristics#3)-content-that-guides-users): Where relevant, headings, subheadings, tabs, bullet-point lists, field labels, and so on are used to break up content and to help users quickly scan the page.

We are also including more information and methods on this in the new UX writing course. For example, [this page illustrates common reading patterns ](https://pages.github.ibm.com/TOMERTON/ux-writing-course/hierarchy/2/#some-common-reading-patterns)and discusses that, since people often scan a page, the writer should Include the most important points in the first sentence or two of any section. I deemed the point about IBM authentication important enough to warrant its own section so that it wouldn't be hidden at the end of a paragraph (burying the lede).

The return helps break up the new concept of _what_ a local system is and _who_ is able to access them. This is something I want to really highlight because it impacts internal and open source users very differently. 

I'm definitely open to additional suggestions (for example I merged your last suggestion on taking out a return because the point I was highlighting wasn't so important as this one.)
