### ISSUE TITLE
Common MDX errors problem/solution design pattern

### ISSUE THREAD

**Issue by jdharvey-ibm** [carbon-design-system/carbon-platform#1176]
Relates to: #1123

We'd like to have a general design pattern for how to write/phrase/display each entry on the common mdx errors page.

Each entry is a description of an error that occurred while processing an MDX file and some details about how to resolve that error.

As far as the resolution steps, development can generate the content for these entries, but dev is looking for guidance about best practices for presenting that information to the viewer.

**Comment by kingtraceyj** [comment]
Design file for MDX error patterns: https://www.figma.com/file/WyfqQh9R1VXYZErfmsNDVH/Platform_MDXerrors?node-id=317%3A11967

**Best practices when writing about errors:**
This paragraph can explain the error is and how to troubleshoot. Description should address the basic who, what, when, why and hows.

Who caused the issue? If the problem is our fault, how do they reach out to get more information and are there other options?

What happened & why did this happen? The more specific you can be about the error the better. Try and name exactly what happened and why—you can be as technical as needed since we now how room to explain what’s goinging on in the backend to cause this error.

When will this be solved? If this is an error from our end, let the user know when expect to problem to be solved. 

What are the steps the users need to fix the problem? Again, the more specific you can be about how to exactly solve the problem the better. You can include any additional links that the user might need to troubleshoot.
