### ISSUE TITLE
Code snippet style bug

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#1196]
Scroll bar should be flush to the right

Adding `width:100%` to ` .cds--snippet-container ` should fix this.

https://next.carbondesignsystem.com/libraries/carbon-components-angular/latest/pages/tutorial/step-1
<img width="821" alt="Screen Shot 2022-08-31 at 10 14 30 AM" src="https://user-images.githubusercontent.com/2753488/187714745-b7912ba4-39d0-4ccd-961d-a7a9a0e30ab6.png">

**Comment by mattrosno** [comment]
This isn't noticeable if OS scrollbars auto hide. Since this bug is visible on desktop, we the site has a lot of code snippets, and the fix appears to be small, I'm comfortable adding it to v1.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/1691245/187728586-623fb34b-a39a-4b61-bccc-7c8e057e49dc.png">

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1196?planning-poker) with Zenhub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
