### ISSUE TITLE
Convert all SSG pages that use remote content to ISR

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#1200]
**Summary**

What problem (or opportunity) are we solving? Why are we solving it? Is there supporting user
conversations or research?

We want content to be updated on production without having to redeploy, therefore let's have pages revalidate every hour.

**Job stories**

What value will this deliver?

When remote content consumed by the application is changed, I want to see the updated versions in the web app without the need of a deployment, so I can read the most up to date content.

**Acceptance criteria**

What requirements must be met to complete this request?

1. getStaticProps pages have a revalidation of one hour across the app if they are reading remote content (whether its our own data graph, github, medium, etc...)) (most are)

**Comment by mattrosno** [comment]
The GitHub response cache is 1 hour. If revalidation is an hour, that means the maximum stale content window could be 2 hours? If so, do we want revalidation to happen more frequently, since that won't increase our likelihood of GitHub API rate limiting?

**Comment by mattrosno** [comment]
I'll add to our v1 release because we'll want to prevent overly-stale content when more people are using the web app.

**Comment by francinelucca** [comment]
> The GitHub response cache is 1 hour. If revalidation is an hour, that means the maximum stale content window could be 2 hours? If so, do we want revalidation to happen more frequently, since that won't increase our likelihood of GitHub API rate limiting?

I don't necessarily have a preference, @jdharvey-ibm  should we do 30/20mns instead? or stick to the hour? 
The case where the page revalidates just before the github cache renews, making the 2hour window, seems improbable enough to happen?

**Comment by mattrosno** [comment]
https://nextjs.org/docs/basic-features/data-fetching/overview

I don't see any need for SSR or CSR right now.

If the page requires any external data (not in this repo), let's do ISR.

If the page doesn't require any external data (no remote GitHub repo data, no remote MDX, etc.), the default SSG works for me. If our build times are getting too big from SSG pages, we could reduce the number of SSG pages to just the home page, and have everything else be ISR.

**Comment by jdharvey-ibm** [comment]
If you think about this as a tiered cache, we want the cheapest and most "defensive" caching to be closest to the users (at the "edge", like a CDN). It's similar to computer architecture, where you want to do everything you can to avoid the CPU having a cache miss and needing to query the RAM. Same for the RAM. You want to avoid having to defer to the HDD or SSD as much as you can. The only difference is that the variable we have to play with in a web-app is duration as opposed to space.

The web-app, being the closest to the edge, should be the main decider of how long a resource stays valid, since it's the least expensive (CPU-wise) when handling requests; anything that isn't cached by the web-app is going to burn more CPU across the platform (e.g. CPU of rabbitmq, data-graph, logging, etc.).

If the maximum amount of time we want a user to see the same version of a page is 1 hour, we should start there at the web-app and work backwards.

Requests that "fall through" the cache will hit more platform resources (like data-graph and github APIs and stuff). Taking github APIs as an example, the question is: How often do we anticipate the GH queries we're making to generate new content *versus* how often do we expect to call those APIs.

- For an API we hit very infrequently, but it's data changes every time we do, we want that GH request to have an extremely low TTL (or none at all)
- For an API we hit all the time, but it almost never changes, maybe an hour TTL is sufficient for that one. That puts the max staleness at 2 hours, but for this particular API, maybe that's what makes the most sense.
- For an API we hit all the time AND it changes very frequently, we get to decide what the right cost/benefit is for a TTL. We want to hit the origin API *as much as possible without exceeding our rate limit or adversely affecting load time*.
   - If it's a fast API, then we keep our TTL low.
     - But if we start hitting our rate limit, we increase the TTL out of necessity.
   - If it's a slow API, we strike a balance, and maybe that's 5 or 10 minutes as the TTL, meaning that the effective maximum lifespan of the page in question is 1h10m.

Anyway, (generally speaking) keep the edge caching TTL high and the internal caching low, with an asterisk next to the internal caching.

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-624c3fc8b7972e001130fef7/issues/carbon-design-system/carbon-platform/1200?planning-poker) with Zenhub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm
