### ISSUE TITLE
Need to specify externalDocsUrl for IBM Products

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-platform#1380]
There's currently no way to access IBM Products PAL documentation from asset detail pages. 

@mattrosno says that this looks like indexing bug where we need to specify externalDocsUrls.

I haven't done an exhaustive check, but it doesn't look like it's affecting IBM.com web components at least. Will look at some other PAL libraries to make sure.

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/e781f84f-5a92-47f2-8810-7dbec490f5e9)

**Comment by mattrosno** [comment]
I downgraded to sev 2, because the workaround exist by navigating directly to the external site. E.g.: https://pages.github.ibm.com/cdai-design/pal/patterns/creation-flows/usage/#full-page

<img width="660" alt="image" src="https://user-images.githubusercontent.com/1691245/193649094-dd352589-2d55-441b-8d17-982287e22185.png">

**Comment by mattrosno** [comment]
Closing this because the PR with fixes has been submitted.
