### ISSUE TITLE
Show open issue and PR counts per asset and link to them

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#372]
**Old tasks**

- Add GitHub label to assets schema so we can query open issues and pull requests
- Query GitHub repo issues with that label when we fetch data and populate the data model with the results
  - Will this count get updated throughout the day with ISR
- Render issue and PR counts in asset detail page and link out to the list of GH issues or PRs so you can see those details
- Edge / empty states
- Documentation on how to use these labels

**New tasks**

- See comment

**Comment by mattrosno** [comment]
E.g. https://github.com/carbon-design-system/carbon/issues?q=is%3Aissue+is%3Aopen+label%3A%22component%3A+combobox%22

**Comment by alisonjoseph** [comment]
Do we only want to reply on labels? Or should we all query the component name in issue titles?

Carbon-charts treemap search example
https://github.com/carbon-design-system/carbon-charts/issues?q=is%3Aissue+is%3Aopen+treemap+in%3Atitle

**Comment by andreancardona** [comment]
> Do we only want to reply on labels? Or should we all query the component name in issue titles?
> 
> Carbon-charts treemap search example https://github.com/carbon-design-system/carbon-charts/issues?q=is%3Aissue+is%3Aopen+treemap+in%3Atitle

I feel like we should query for the component name in the title as well - to capture all of the activity around that component. Thoughts?

**Comment by jdharvey-ibm** [comment]
@alisonjoseph You raise really good points and it makes me question a little bit the value-add of these versus the cost for us and the library maintainers.

I can definitely see these being useful metrics at the library-level, but I'm not convinced at the individual asset level. We'd be enforcing conventions on how people manage their issues and development process by forcing them to provide labels or certain keywords, which might not be in their best interest with how they prefer to manage their codebase and issues. 

Also, if the labels are forgotten or are anything other than perfect, these counts will be off. Same thing would go for almost any algorithm we could devise to search for per-asset issues.

At the library-level, we could pull the `package.json`'s `bugs.url` field to have _them_ tell _us_ where to look for issues.

At the time of writing, there's not a single PR in the entire carbon monorepo that has an asset label or other identifier, so for every single asset in the carbon monorepo, the PRs field will show up as zero or blank. The issues are prone to the same problem. Some of them have labels, some of them don't. Some have titles which make the affected component obvious, some don't. Some have titles which don't mention a component or they have no labels, but their content makes it apparent which component is relevant.

Monorepos present an additional challenge here too because PRs and issues are not often labeled in a meaningful way to distinguish between which package in the monorepo they're relevant to. So in the case of the carbon monorepo, each of its libraries would either show up as zero or "26" (the count of all PRs as the moment). npmjs.com has this same issue and does the latter (showing a count of *all* issues in the containing repo). https://www.npmjs.com/package/@carbon/react

**Comment by mattrosno** [comment]
After discussing with the platform squad devs, we determined:

1. We don't want to add GitHub labels to the schema because it's really time consuming to apply those, and even though the system squad does that in Carbon's monorepo, not all library maintainers do that
2. No need to render pull request counts anywhere. Ideally, PR review is prompt and count hovers near zero.
3. Nothing of value to render on library detail page because when multiple libraries come from the same repo, there's no good way to know which issues are relevant to which library
4. Per asset, query result count for open issues searching issue title, dashboard item heading "Open issues"
5. Per asset, query result count for discussions searching discussion title, dashboard item heading "Discussions"
6. For both of those, we're searching asset name not id, because the name can evolve but id needs to be stable
7. If result count is 0, show 0 and still out to it so people can then do additional issue and discussion searches in GitHub

**Comment by mattrosno** [comment]
One other thing we discovered - searching discussions is supported in the GitHub GraphQL API but not through OctoKit. We're currently using OctoKit. It doesn't make sense to use a totally new API right now, but in the near future we'll be able to when we build out our content service. Until then, the best thing we can do is render an en dash for discussion count and have that card take you to the repo's discussions pre-searched by the asset name.
