### ISSUE TITLE
Update to Stylelint 14

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#63]
Upon adding `"stylelint.validate": ["css", "less", "postcss", "scss"]` to VS Code settings.json, VS Code prompted this warning to update to Stylelint 14. I see we're currently using v13 in our package.json.

https://github.com/stylelint/vscode-stylelint#migrating-from-vscode-stylelint-0xstylelint-13x

**Comment by jdharvey-ibm** [comment]
I looked into this along with the eslint 7 -> 8 upgrade. The problem is that in both cases, our dependency on eslint and stylelint is driven by the carbon design system packages which we are extending.

If/when the carbon packages are updated, this can be revisited, but at the moment there's no easy way for us to modify the carbon configs we are extending to remove things like deprecated props.
