### ISSUE TITLE
Local system, team, and resource naming principles

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#661]
We need squad alignment on naming conventions across the system.

# Proposal A

## Systems

Our system is `Carbon Design System`. The short name is `Carbon`. The namespace used in code to prevent conflicts and collisions is `cds`. The scope used in npm is `@carbon`.

Since Carbon is a system of systems, we have the global `Carbon Design System`, and local systems that include increased specificity with:

- Local governance 
- Local guidance
- Local design kits, libraries, assets (collectively, "resources")

Local systems calibrate Carbon's website for a specific group of makers and can be configured to 1) remove unused global resources, and/or 2) add local resources.

Local systems aren't for a specific platform (e.g. iOS/Android). Local systems aren't for a specific tool or technology (e.g. React). That's what design kits, libraries, and assets are for. (Assets have a `platform` key with `web` or `cross-platform` values. See more on library naming below.)

It's important that local systems are structured against groups of people, as any given group of people may be using multiple platforms, tools, and technologies. When building a product or digital experience, we don't want our users having to constantly switch systems to do their job. That would go against Carbon's value proposition as a platform of contextualized experiences.

As local systems are **for** groups of people, we use the naming convention `Carbon for ___`. Some examples:

- `Carbon for IBM.com` is Carbon's local system for IBM.com designers, developers, and product managers (aka "makers".)
- `Carbon for IBM Products` is Carbon's local system for IBM Software employees building IBM products.
- `Carbon for Cloud` provides additional specificity and locality for IBM employees building IBM Cloud products as an extension of its parent `Carbon for IBM Products` local system.

In the future, we've identified the need for local systems to be at the per-product basis. This naming convention still holds up as `Carbon for [Product Name]` as the local system for Product Name makers.

Carbon's website will have a top-left system switcher that allows you to navigate between the global `Carbon Design System` and local `Carbon for ___` systems.

## Teams

We have the concept of sponsor teams so when browsing design kits and libraries, you can see if there is an IBM team committed to maintaining each resource. It's not a monetary sponsorship or anything, but a sponsorship of time for upkeep, support, and new features.

So far, our identified teams are `Carbon`, `IBM.com`, `IBM Cloud`, `IBM Security`, `IBM AI Apps`, `IBM Watson`, and `IBM Products`.

There is no `Carbon for` in team names. Team names _could_ directly align with local system names so the `Carbon for IBM.com` system uses libraries maintained by the `IBM.com` team, but separating team and system naming provides optionality so going forward, the `IBM.com` team could get renamed to `Carbon Dotcom` if we wanted to better map to Carbon's current squads, etc.

## Resources

The only requirement for resource naming is that they also don't use the `Carbon for ___` naming convention. It's common to use `Carbon ___` where the `___` is a tool or technology like `Carbon React`.

Not all libraries need `Carbon` in the name. We don't currently have any governance in place for this, but it'd be good to have a process in place to approve the use of `Carbon` in any name to ensure the new resource aligns with our system's mission and that it meets Carbon's expectations in terms of maintenance, support, resourcing, etc.

### Libraries

There's no requirement for a library's name to exactly match its npm package name if it has a package (e.g. `Carbon React` and the `@carbon/react` code package that it publishes). Names change, packages become aliases of other packages, etc. Being less strict on library/package naming alignment enables our system to evolve over time as needed.

### Assets

Every asset belongs to a library. Although discouraged, there can be a `Card` asset in library A, and a `Card` asset in library B. The only requirement is that there can't be two `Card`s in the same library. (Technically, there can be as long as their `id`s are different.)

If it becomes unavoidable for two assets to share the same name, they each belong to different libraries which will provide differentiation, and each library could have different sponsoring team which would provide additional context.

**Comment by kingtraceyj** [comment]
@mattrosno what kind of design outcomes are you looking for here?

**Comment by mattrosno** [comment]
@kingtraceyj 

>We need to align on naming conventions across the system.

This is so we can start using consistent naming in platform v1 pages (Designing > Getting started) and in platform v2 designs.

**Comment by ljcarot** [comment]
`Local system` makes sense as a distinction from the global system but it doesn't feel like a term that we want all over the website.  Are we simply agreeing there's local systems and global system amongst ourselves for this exercise and that our local systems follow 'Carbon for ___'.   If we plan to break the naming of PALs, we need a better name than local system.

**Comment by ljcarot** [comment]
`Teams` is a bit vague.  From your description above, we should call them 'Maintainers'.  Current label of `Sponsor` doesn't give the same level of ownership.  I'd also like to review the current list of values with Steering Committee especially if this is something that can be used to filter by.

**Comment by mattrosno** [comment]
@ljcarot your comment on teams vs maintainers... we have:

- Contributors: individuals that contribute to a Carbon project any any way (should that be as simple as opening a bug, commenting on an issue, or making an actual design or code contribution.) A community member is a contributor if they participate in any way and others benefit from that participation.
- Maintainers: contributors that have elevated "write" permissions who have the ability to review, accept, and merge in contributions.

As Carbon is open-source, we structure our projects so there can be external (non-IBM employee) maintainers on a per-project basis.

Carbon React for example - it isn't accurate to say that the Carbon core team maintains (or "owns" per your comment) it because that implies that there are no Carbon React maintainers outside of the Carbon core team or outside of IBM.

It's more accurate to state that the Carbon core team "primarily maintains" the Carbon React library. "Primary maintainers" becomes wordy when used across the Carbon website.

The idea of an IBM team sponsoring one or more Carbon libraries was influenced by GitHub Sponsors: https://github.com/sponsors. As stated in proposal A, this isn't a direct, monetary, sponsorship, but it states that an IBM team is investing their time and resources to primarily maintain one or many Carbon projects, which is what our users want to know. See the "wow" in hill 1A:

https://app.zenhub.com/workspaces/platform-product-management-624ca9397d28730018df40c2/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvNzY2ODM

You can also see the "sponsor" relationship here:
![Experience System ERD - FINAL (1)](https://user-images.githubusercontent.com/1691245/171197976-af23a64a-9334-4886-b1f6-27823c3fb3a5.png)

**Comment by ljcarot** [comment]
@mattrosno Local system is acceptable but not tremendously user friendly.  It will be a challenge to get people to shake the term PAL, unless there is an equal or better label.  The closest term that is emerging is C4Products, C4dotcom, C4AEM, etc.  So PAL (current) = Local system (internal term) = C4____(external term).

**Comment by kingtraceyj** [comment]
Design worked through some of the language for proposal B in this figma:
https://www.figma.com/file/3zTomtMk9JGI0IwcUlqInh/Naming-Convention-%26-Content-Guidelines?node-id=0%3A1

This is still drafty but wanted to go ahead and get it out there for discussion.

# Proposal B

## Systems
Our system is Carbon Design System. The short name is Carbon. The namespace used in code to prevent conflicts and collisions is cds. The scope used in npm is @carbon.


Since Carbon is a system of systems, we have **Carbon core system** and **Carbon extended system** which include increased specificity with:

- Governance
- Guidance
- Design kits, libraries, assets (collectively, "resources")


**Carbon extended systems** extend Carbon core system for a specific group of **creators** that have an audience with specific design and dev needs.  
**Carbon extended systems** are platform, tooling and framework agnostic.  


It's important to note that Carbon extended systems are mapped to audiences which are made up of **multi-disciplinary** groups of creators, as any given group of people may be using multiple platforms, tools, and technologies. 


**Carbon extended systems** are for groups of people who have a specific purpose, intent and audience, so we use the naming convention Carbon for ___ to specify that audience.  
Some examples:
Carbon for IBM.com is Carbon's extended system for IBM.com designers, developers, and product managers (
Carbon for IBM Products is Carbon's extended system for IBM Software teams building IBM products
Carbon for AEM is Carbon's extended system for marketing teams building with AEM

## Maintainers
We have the concept of maintainers so when browsing design kits and libraries, you can see if there is a team or individual committed to maintaining a resource. 


Maintainer's names are self-identified as the point of contact for resources. 


There is no Carbon for ___ in maintainer names. Maintainer names could directly align with Carbon extended system names so the Carbon for IBM.com system uses libraries maintained by the IBM.com team, but separating team and system naming provides optionality so going forward, the IBM.com team could get renamed to Carbon Dotcom if we wanted to better map to Carbon's current squads, etc.

## Resources
No change

**Comment by mattrosno** [comment]
Both issues are closed, so closing this epic.
