### ISSUE TITLE
Come up with solution for what to use to replace component demos

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-platform#763]
Collaborate with system squad and determine solution to replace component demos on the site. 

Should we use Storybook embeds? Something else?

Do we need:
- Theme switcher?
- Variant switcher?
- Copy/paste source?
- Interactive controls?
- Click out to Storybook or something else to explore all available props?
- How to handle both tall and short demos? (Use aspect ratio for container?)

Acceptance criteria:
- [x] Technical proof of concept to demonstrate embed options
- [x] Development constraints shared with design team so design specs can be created
- [x] Alignment on how live demos will be placed on pages (via schema or MDX)

**Comment by mattrosno** [comment]
Notes from today:

- At minimum, for website audiences, we want to demo a component by viewing it in different themes and viewing its variants, and we could link out to external demo sites (e.g. Storybook) for complex interactions like modifying controls, copying source code, etc.
- We should explore an embed wrapper that sets embed URL parameters like color theme and possibly story and story configuration.
- That means we'd want to publish a Storybook configuration package so we can standardize across all ecosystem Storybooks so they all have the same URL options for theme, etc.
- The Storybook embed would likely be "canvas only" with no toolbar, no docs or code snippets, etc.

Outstanding questions:

1. Would we have to support Storybook embed height configuration to hardcode heights? Or would we be able to dynamically set iframe heights ([example](https://medium.com/@kaptenadhoc/how-to-make-an-iframe-automatically-resize-to-fit-its-content-31593ff54f01))? Would there be any cross-origin blockers in doing so?
2. How would we handle versioning if we rely on Storybook embeds for documentation live demos? Even if we host versioned Storybook sites (which is no small ask), Carbon website versioning will be more robust. For example, let's say you're viewing an older version of a component docs like [v0.55.1 Area component](https://next.carbondesignsystem.com/assets/carbon-charts/v0.55.1/area-simple). For every embed, in our wrapper, do we need to call out that the embed is demonstrating the [latest version of the component](https://charts.carbondesignsystem.com/iframe.html?id=simple-charts-area-simple--area-time-series-natural-curve)? (Storybook embed URLs aren't versioned `v0.55.1` like Carbon platform.)
3. How long will it take for Storybook embeds to render? Will it be noticeably bad? Acceptably bad? Non-issue?
4. Does this mean we'd need a story for every non-image example shown in website? Because Storybook doesn't expose subcomponent controls, we can't put a component in any state through URL alone. We'd need a bespoke story in Storybook for each unique demo shown in website. Is that a bad thing? Could we have a convention in Storybook that stories in a "Demos" directory per component exist for website documentation?
5. What sanitization would be needed so Storybook embeds aren't misused?
6. If we wanted to demo specific code versions, are there other good options like CodeSandbox or StackBlitz that act as instant, just-in-time, dev environments?

**Comment by alisonjoseph** [comment]
> 1. Would we have to support Storybook embed height configuration to hardcode heights? Or would we be able to dynamically set iframe heights ([example](https://medium.com/@kaptenadhoc/how-to-make-an-iframe-automatically-resize-to-fit-its-content-31593ff54f01))? Would there be any cross-origin blockers in doing so?

Need to test this, ideally we could dynamically set height. 

> 2. How would we handle versioning if we rely on Storybook embeds for documentation live demos? Even if we host versioned Storybook sites (which is no small ask), Carbon website versioning will be more robust. For example, let's say you're viewing an older version of a component docs like [v0.55.1 Area component](https://next.carbondesignsystem.com/assets/carbon-charts/v0.55.1/area-simple). For every embed, in our wrapper, do we need to call out that the embed is demonstrating the [latest version of the component](https://charts.carbondesignsystem.com/iframe.html?id=simple-charts-area-simple--area-time-series-natural-curve)? (Storybook embed URLs aren't versioned v0.55.1 like Carbon platform.)

Could we have an asterisk when viewing older versions with a note that the demo is the latest version? I think its unrealistic for storybook to have all the versions published. 

> 3. How long will it take for Storybook embeds to render? Will it be noticeably bad? Acceptably bad? Non-issue

There is a slight delay, I put together a quick demo updating storybook url parameters

https://user-images.githubusercontent.com/2753488/173480154-033a30bb-f10f-41f9-8c68-aa5b947fa0eb.mov

> 4. Does this mean we'd need a story for every non-image example shown in website? Because Storybook doesn't expose subcomponent controls, we can't put a component in any state through URL alone. We'd need a bespoke story in Storybook for each unique demo shown in website. Is that a bad thing? Could we have a convention in Storybook that stories in a "Demos" directory per component exist for website documentation?

Yes, we'd need a story for an demo we want to show, but I think thats ok. We have flexibility here on what makes the most sense to demo per component.

> 5. What sanitization would be needed so Storybook embeds aren't misused?
🤔 

> 6. If we wanted to demo specific code versions, are there other good options like CodeSandbox or StackBlitz that act as instant, just-in-time, dev environments?

StackBlitz seems to be a no-go, and codesandbox is slow, but doable. 

![Screen Shot 2022-06-13 at 9 31 19 PM](https://user-images.githubusercontent.com/2753488/173480974-be6e5301-6cec-4d51-81b8-bc8e0b47428f.png)

**Comment by tay1orjones** [comment]
@alisonjoseph Since we know the predefined parameters available via the dropdowns, could we [preload or prefetch](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload) them to eliminate the delay?

In theory we could dynamically add link tags to the page with something like 

```html
<link rel="preload" href="https://storybookurl.com/iframe.html&parameter=something" as="document">
```

**Comment by alisonjoseph** [comment]
yea thats slow
https://user-images.githubusercontent.com/2753488/173603394-6436092b-b0d6-4fbc-afbc-9a59f6d98889.mov

**Comment by mattrosno** [comment]
Embed heights - for simplicity, it seems like we'd want to support a small, medium, and large embed heights and be comfortable knowing that embed scrollbars will happen on occasion. Then, later on we attempt to optimize with that `postMessage()` idea above if we want.

If we're supporting various embed sizes:

- What are those height sizes?
- Are we also supporting width sizes too (e.g. different embed frame visuals based on number of columns the embed is using?)
- Would we want these supported embed sizes following aspect ratios?

**Comment by mattrosno** [comment]
@alisonjoseph on iframe loading - I recommend quickly trying the frame `onload()` event and if that fires well after the iframe's component visibly renders... then it's not a dependable way for us to hide/show any sort of loading animation, and if that's the case I recommend no loading and we look into `postMessage()` optimizations later.

**Comment by mattrosno** [comment]
Version disclaimer - the only thing that platform will know is embed URL. Example:

https://react.carbondesignsystem.com/iframe.html?id=components-button--default&globals=theme:g10

That embed URL doesn't encode a version anywhere.

It would be nice for there to be a version disclaimer that we show in the footer of all embed frames that says something to the extent of:

> **View full demo** for additional information such as its version, controls, and API documentation.

That "View full demo" would link you to this:

https://react.carbondesignsystem.com/?path=/story/components-button--default&globals=theme:g10&viewMode=story

It's important to let our users know that the demo might not exactly match the version of the documentation that they are viewing. It's also nice to link out to the full canvas so they can play with the controls, view the API docs, etc.

**Comment by mattrosno** [comment]
Schema considerations - how will we get this on the asset overview page?

**Option 1 - Add to schema**

We could add an [asset key](https://github.com/carbon-design-system/carbon-platform/blob/main/docs/resource-schemas.md#asset-keys) to the schema like `storybookEmbedUrl`. But it'd actually be more complicated than that, because we'd need to specify options like embed height, embed width (number of columns), etc. It also brings up questions:

- What if the live demo needs to be something else like CodeSandbox?
- What if the demo needs to temporarily be a static image instead (e.g. patterns that don't have Storybook stories where we'd want an image of the pattern on the overview page?
- What happens if we'd like to show more demos in other pages like to explain usage, or code, etc.?

I believe there's a better option...

**Option 2 - StorybookEmbed MDX component**

We'll likely want to make a custom MDX component for Storybook embeds so we can embed demos throughout pages. The MDX component would have props to set the embed URL and its dimensions.

That means we'd add an `overviewPath` to the [asset `docs` key](https://github.com/carbon-design-system/carbon-platform/blob/main/docs/resource-schemas.md#asset-docs) so there's an MDX file that would fill a slot in the overview pages. That slot would go between the dashboard and the structured data at the bottom of the page for schema-driven content (related assets, etc.)

By doing this, an asset could just put a static image in there if needed when there isn't a Storybook embed (e.g. patterns) so the asset overview pages still show the asset (even if it's not "live").

This also sets us up to support other demos in the future if we want MDX components for CodeSandbox, etc. embeds.

Having an MDX "slot" in the middle of the overview page opens it up for asset maintainers to put other content in there, but especially during this first release, we can actively monitor that to ensure the markdown portion of the asset overview page just gets used as intended (live demos.)

**Comment by alisonjoseph** [comment]
Agreed that **option 2** feels like a better choice, the amount of configuration options we would need to add the demo to the schema doesn't seem scalable.

**Comment by alisonjoseph** [comment]
Closing this as done ✅  

Will open a new issue to build this component when design spec https://github.com/carbon-design-system/carbon-platform/issues/882 is done.
