### ISSUE TITLE
Render asset page tab content MDX

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#793]
After asset documentation can be indexed through the schema:

- [x] Generate page tab and route for each usage, style, code, and accessibility content that has been indexed (if none exist, each asset will only have the Overview tab)
- [x] Render that remote MDX (can be relative or absolute path, see comments on https://github.com/carbon-design-system/carbon-platform/issues/792)
- [x] Scrub out `tabs` frontmatter? (See below.)
- [x] Use GitHub call to check for the existence of asset docs defaults in determining which page tabs to include

**Tabs frontmatter**

If you look at legacy Carbon website markdown for component documentation (e.g. https://raw.githubusercontent.com/carbon-design-system/carbon-website/main/src/pages/components/accordion/usage.mdx), you'll see `tabs` frontmatter keys that tell each page what sibling pages exist to render in the page tabs.

```markdown
---
title: Accordion
description:
  An accordion is a vertically stacked list of headers that reveal or hide
  associated sections of content.
tabs: ['Usage', 'Style', 'Code', 'Accessibility']
---
```

We won't need that anymore, because the schema additions from https://github.com/carbon-design-system/carbon-platform/issues/792 will determine which page tabs should be available.

Does that means we just ignore the `tabs` frontmatter for asset documentation pages? Or do we scrub it when we parse the markdown file?

**Comment by mattrosno** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Product-Management-624ca9397d28730018df40c2/issues/carbon-design-system/carbon-platform/793?planning-poker) with ZenHub @alisonjoseph @andreancardona @francinelucca @jdharvey-ibm

**Comment by francinelucca** [comment]
Have a pretty functional POC of this over on #936; 
Adding #321 dependency and deferring because no 'Code' or 'Usage' tabs will work due to `ComponentDemo` not being an existing component on platform and on top of that a lot of 'Accessibility' pages are using imports which 'cause the page to crash since we aren't handling that yet
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/40550942/176789775-183384b7-1f3f-46e5-9f79-76f9c3b5ddeb.png">
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/40550942/176790674-5ecccd43-bdda-4ff5-9981-6e7dc7895d17.png">

**Comment by francinelucca** [comment]
Needs clarification on what tabs look like when no side page-navigation 
![image](https://user-images.githubusercontent.com/40550942/176790805-42055815-3e86-42eb-83b4-4841a4576673.png)
VS
![image](https://user-images.githubusercontent.com/40550942/176790823-c39561d1-eb6f-414f-8da4-4669e8a92fa3.png)
